CREATE TABLE messages (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender VARCHAR2(50) NOT NULL,            -- 발신자
    receiver VARCHAR2(50) NOT NULL,          -- 수신자
    content CLOB NOT NULL,                   -- 메시지 내용 (긴 텍스트를 위해 CLOB 사용)
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- 메시지 전송 시간
);

SELECT id FROM Messages;

DROP TABLE Messages;